# Generated by Django 2.0.2 on 2018-03-15 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.IntegerField(unique=True)),
                ('mobile_money_phone', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_money_name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payiTGhana_App.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('type', models.CharField(max_length=20)),
                ('sms', models.IntegerField()),
                ('confirmed', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payiTGhana_App.Client')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pledged_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_confirm', models.CharField(max_length=20)),
                ('payment_deadline', models.DateTimeField()),
                ('maturity_date', models.DateTimeField()),
                ('transaction_code', models.CharField(max_length=10, unique=True)),
                ('status', models.IntegerField()),
                ('matched', models.IntegerField()),
                ('repledged', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pledge_maker_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payiTGhana_App.Client')),
                ('pledge_receiver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='payiTGhana_App.Client')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=200)),
                ('sender', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='pledge_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payiTGhana_App.Pledge'),
        ),
    ]
