# Generated by Django 2.0.2 on 2018-02-10 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payiTGhana_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('type', models.CharField(max_length=20)),
                ('sms', models.IntegerField()),
                ('confirmed', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pledged_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_confirm', models.IntegerField()),
                ('payment_deadline', models.DateTimeField()),
                ('maturity_date', models.DateField()),
                ('transaction_code', models.CharField(max_length=10, unique=True)),
                ('status', models.IntegerField()),
                ('matched', models.IntegerField()),
                ('repledged', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='pledge',
            name='pledge_maker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payiTGhana_App.Client'),
        ),
        migrations.AddField(
            model_name='match',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payiTGhana_App.Client'),
        ),
        migrations.AddField(
            model_name='match',
            name='pledge_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payiTGhana_App.Pledge'),
        ),
    ]
