# Generated by Django 2.0.2 on 2018-02-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payiTGhana_App', '0003_auto_20180210_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='referrer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
