# Generated by Django 2.0.2 on 2018-02-11 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payiTGhana_App', '0004_client_referrer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=200)),
                ('sender', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payiTGhana_App.Client')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
